index_reference:
  threads: 1
  mem_mb: 4000
  runtime: 1h

mappability:
  threads: 1
  mem_mb: 4000
  runtime: 1h

fastp:
  threads: 1
  mem_mb: 4000
  runtime: 1h

bwa_mem:
  threads: 1
  mem_mb: 4000
  runtime: 1h

dedup:
  threads: 1
  mem_mb: 4000
  runtime: 1h

filter_bam:
  threads: 1
  mem_mb: 4000
  runtime: 1h

mosdepth:
  threads: 1
  mem_mb: 4000
  runtime: 1h